Module2 task3
htmlacademy-adaptive/165855-sedona-22 pull request #6
Opened 2021-04-08 06:17 UTC by Unshady91

2021-04-08 15:16 UTC, costigans requested changes

2021-04-08 15:16 UTC, costigans commented on source/catalog.html
> +  <title>Фото и видео</title>
Зря убрал «название сайта».
Есть несколько популярных способов именования заголовков страницы, например:
Название страницы — Название сайта
Название страницы | Название сайта
Название страницы / Название сайта
Название страницы. Название сайта
и т.п.

2021-04-08 15:16 UTC, costigans commented on source/catalog.html
> +<body class="page__body page__body--inner">
Правильно используешь модификатор 👍

2021-04-08 15:16 UTC, costigans commented on source/catalog.html
> +    <section class="main__content main__content--wrapper">
А где блок `main`?

2021-04-08 15:16 UTC, costigans commented on source/catalog.html
> +      <h2 class="content__title">Фото и видео</h2>
А где блок `content`?

2021-04-08 15:16 UTC, costigans commented on source/catalog.html
> +              <h3 class="content__header content__header--wrapper">
Одни и те же классы, точно будет конфликт

2021-04-08 15:16 UTC, costigans commented on source/catalog.html
> +              <button class="button content__button">
Вот здесь правильный микс блока и элемента.
Блок отвечает за внешний вид «объекта», элемент — за положение относительно родительского блока (`content`)

2021-04-08 15:16 UTC, costigans commented on source/catalog.html
> +              </button>
А если этот файл иконки не загрузятся или случайно удалят с хостинга, что останется на кнопке?
Пользователю будет понятно, что произойдёт по нажатию?

2021-04-08 15:16 UTC, costigans commented on source/catalog.html
> +                </svg>
Почему решил инлайнить?

2021-04-09 05:21 UTC, Unshady91 commented on source/catalog.html
> +              <h3 class="content__header content__header--wrapper">
не внимательность тут content__title у заголовка должно быть

2021-04-10 04:03 UTC, costigans commented on source/catalog.html
> +  <title>HTML Academy: Седона | Фото и видео</title>
Поменяй название страницы и сайта местами.

2021-04-10 04:03 UTC, costigans commented on source/catalog.html
> +                <img class="content__icon" src="img/icons/like.svg" width="23" height="21" alt="Кнопка нравится">
То что это кнопка, и так понятно по тегу `button`

2021-04-10 04:03 UTC, merged